apiVersion: v1
kind: Service
metadata:
  name: amcp-agent-context
  namespace: amcp-system
  labels:
    app: amcp
    component: agent-context
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: mobility
    port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: amcp
    component: agent-context
---
apiVersion: v1
kind: Service
metadata:
  name: amcp-agent-context-headless
  namespace: amcp-system
  labels:
    app: amcp
    component: agent-context
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: mobility
    port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: amcp
    component: agent-context